version: '3'
services:
  web:
    build: .
    command: sh -c "sleep 7 && python manage.py migrate && gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application"
    depends_on:
      - postgres
# Don't really need it
#    volumes:
#      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: healthcheck/postgres:alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
      POSTGRES_HOST_AUTH_METHOD: trust
